#!/usr/bin/env bash
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ls='ls -F --color=auto'
alias ll='ls -lah --color=auto'
alias psync='rsync -avh --info=progress2'
alias dusage='du -Sh | sort -n -r | less'
alias topmem='ps h -eo pmem,comm | sort -nr | head'
